apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-impl-cm
data:
  definitions.json: |
{{ tpl (.Files.Get "assets/rabbitmq_init/definitions.json" ) . | indent 4 }}
  rabbitmq.conf: |
{{ tpl (.Files.Get "assets/rabbitmq_init/rabbitmq.conf" ) . | indent 4 }}