apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-cm
data:
  index.html: |
{{ tpl (.Files.Get "assets/index.html" ) . | indent 4 }}  
  style.css: |
{{ tpl (.Files.Get "assets/style.css" ) . | indent 4 }}