apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-check
  labels:
    task: {{ .Release.Name }}-{{ .Chart.Name }}
    type: check    
spec:
  schedule: "*/2 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:  
    spec:    
      ttlSecondsAfterFinished: 100
      backoffLimit: 0
      template:
        metadata:
          labels:
            app:  {{ .Release.Name }}-{{ .Chart.Name }}-check
            task: {{ .Release.Name }}-{{ .Chart.Name }}
            type: check    
        spec:
          containers:
            - image: vovchello/checker-message_queue1:latest
              name: check-message
              imagePullPolicy: IfNotPresent
              env:
               - name: RABBIT_HOST
                 value: {{ .Release.Name }}-{{ .Chart.Name }}-impl
               - name: QUEUE_NAME
                 value: {{ .Release.Namespace }}-{{ .Release.Name }}
          restartPolicy: Never
