apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-impl
    task: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-impl
spec:
  ports:
  - name: rabbit-mq
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: rabbit-web
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-impl