apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.task.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.task.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.task.name }}
    spec:
      containers:      
      - image: nginx:alpine
        name: descr
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        resources:
          {{- toYaml .Values.task.impl.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
           name: {{ .Values.task.name }}
           