apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.task.name }}
spec:
  schedule: "*/2 * * * *"
  jobTemplate:  
    spec:    
      backoffLimit: 0
      activeDeadlineSeconds: 100
      template:
        metadata:
          labels:
            app:  {{ .Values.task.name }}
            type: test    
        spec:
          containers:    
          - image: {{ .Values.task.impl.image.name }}
            name: impl
            imagePullPolicy: {{ .Values.task.impl.image.pullPolicy }}
            ports:
            - containerPort: 8888                  
          - image: {{ .Values.task.test.image.name }}
            name: check
            imagePullPolicy: {{ .Values.task.test.image.pullPolicy }}
            env:
    {{- toYaml .Values.task.test.env | nindent 12 }}        
          restartPolicy: Never
