apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.task.name }}
  name: {{ .Values.task.name }}
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80    
  - name: port-2
    port: 8888
    protocol: TCP
    targetPort: 8888        
  selector:
    app: {{ .Values.task.name }}