apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.task.name }}-check
  labels:
    task: {{ .Values.task.name }}
    type: check    
spec:
  schedule: "*/2 * * * *"
  jobTemplate:  
    spec:    
      backoffLimit: 0
      activeDeadlineSeconds: 100
      ttlSecondsAfterFinished: 100
      template:
        metadata:
          labels:
            app:  {{ .Values.task.name }}-check
            task: {{ .Values.task.name }}
            type: check    
        spec:
          containers:                   
          - image: {{ .Values.task.test.image.name }}
            name: check
            imagePullPolicy: {{ .Values.task.test.image.pullPolicy }}
            env:
    {{- toYaml .Values.task.test.env | nindent 12 }}        
          restartPolicy: Never
