apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.task.name }}-impl
    task: {{ .Values.task.name }}
  name: {{ .Values.task.name }}-impl
spec:
  ports:    
  - name: impl-port
    port: 8888
    protocol: TCP
    targetPort: 8888       
  selector:
    app: {{ .Values.task.name }}-impl