# Default values for hoa_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}
podLabels: {}

task:
  name: task-done
  impl:
    image:
      name: vzlobins/task1
      pullPolicy: Never
      tag: ""
    resources: 
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
  test:
    image: vzlobins/checkport
    env:
      - name: TARGET_ADR
        value: "task-done:8888"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false
