apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-landingpage
data:
  index.html: |
{{ tpl (.Files.Get "assets/index.html" ) . | indent 4 }}
  style.css: |
{{ tpl (.Files.Get "assets/style.css" ) . | indent 4 }}