apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: hoa-control-app
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
  name: hoa-control-app
  namespace: {{ .Release.Namespace }}  
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - list
  - watch 
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - watch
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: hoa-control-app
  namespace: {{ .Release.Namespace }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hoa-control-app
  namespace: {{ .Release.Namespace }}  
subjects:
- kind: ServiceAccount
  name: hoa-control-app
  namespace: {{ .Release.Namespace }}