apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /tasks/{{ .Values.task.name }}/logs
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ .Values.task.name }}-logs
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hoa-control-app
            port:
              number: 1323
        path: /{{.Release.Namespace}}/{{ .Values.task.name }}/logs(/|$)
        pathType: ImplementationSpecific      
