apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.task.name }}-descr
    task: {{ .Values.task.name }}
  name: {{ .Values.task.name }}-descr
spec:
  ports:
  - name: descr-port
    port: 80
    protocol: TCP
    targetPort: 80           
  selector:
    app: {{ .Values.task.name }}-descr