apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.task.name }}-impl
  labels:
    task: {{ .Values.task.name }}
    type: impl  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.task.name }}-impl
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.task.name }}-impl
        task: {{ .Values.task.name }}
        type: impl          
    spec:
      containers:    
      - image: {{ required "A valid task.impl.image.repo is required!" .Values.task.impl.image.repo }}/{{ .Release.Namespace }}-{{ .Release.Name }}:latest      
        name: impl
        imagePullPolicy: {{ .Values.task.impl.image.pullPolicy }}
        ports:
        - containerPort: 8888
           