apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /tasks/{{ .Release.Name }}-{{ .Chart.Name }}/logs
#    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ .Release.Name }}-{{ .Chart.Name }}-logs
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hoa-control-app
            port:
              number: 1323
        path: /{{ .Release.Namespace }}/{{ .Release.Name }}/logs
        pathType: Exact      
