apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-check
  labels:
    task: {{ .Release.Name }}-{{ .Chart.Name }}
    type: check    
spec:
  schedule: "*/2 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:  
    spec:    
      ttlSecondsAfterFinished: 100
      backoffLimit: 0
      template:
        metadata:
          labels:
            app:  {{ .Release.Name }}-{{ .Chart.Name }}-check
            task: {{ .Release.Name }}-{{ .Chart.Name }}
            type: check    
        spec:
          containers:                   
          - image: nginx:alpine     
            name: happy-path
            command:
              - /bin/sh
              - -c
            args: [ "if [ $(curl -POST http://{{ .Release.Name }}-{{ .Chart.Name }}-impl:8888 -H 'Content-type: text/plain' -s -d 'tesT12') != 'tesT12' ]; then exit 1; else echo 'happy-path checked'; fi" ]

          - image: nginx:alpine     
            name: allowed-content-type
            command:
              - /bin/sh
              - -c
            args: [ "if [ $(curl  -w '%{http_code}' -s -o /dev/null -POST http://{{ .Release.Name }}-{{ .Chart.Name }}-impl:8888 -H 'Content-type: json/application' -d 'A') != \"415\" ]; then exit 1; else echo 'allowed-content-type checked'; fi" ]

          - image: nginx:alpine        
            name: allowed-method
            command:
              - /bin/sh
              - -c
            args: [ "if [ $(curl -w '%{http_code}' -s -o /dev/null http://{{ .Release.Name }}-{{ .Chart.Name }}-impl:8888) != \"405\" ]; then exit 1; else echo 'allowed-method checked'; fi" ]

          - image: nginx:alpine         
            name:  alpha-numeric-check
            command:
              - /bin/sh
              - -c
            args: [ "if [ $(curl -s  -o /dev/null -w '%{http_code}' -POST http://{{ .Release.Name }}-{{ .Chart.Name }}-impl:8888 -H 'Content-type: text/plain' -d 'X ') != \"400\" ]; then exit 1; else echo 'alpha-numeric-check checked'; fi" ]

          - image: nginx:alpine       
            name: post-size-check
            command:
              - /bin/sh
              - -c
            args: [ "if [ $(curl -s -o /dev/null -w '%{http_code}' -POST http://{{ .Release.Name }}-{{ .Chart.Name }}-impl:8888 -H 'Content-type: text/plain' -d '12345678aB') != \"401\" ]; then exit 1; else echo 'post-size-check checked'; fi" ]

          restartPolicy: Never
