apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-impl
    task: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-impl
spec:
  ports:    
  - name: impl-port
    port: 8888
    protocol: TCP
    targetPort: 8888       
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-impl